# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '13_Contacts_SQLite' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 13_Contacts_SQLite
  pod 'SQLite.swift', '~> 0.11.3'

end
